spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?useSSL=false
    username: root
    password: 12345

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  #jpa Settings
  jpa.hibernate.ddl_auto: create


jwt:
    secret: VWzZpjBOdL464y4Q4WgrdBffl74FKJlPid7lfpEDbT4=
    expiration: 86400000
